version: '3.8'

services:
  shogi_app:
    build: .
    container_name: shogi_app
    restart: always
    depends_on:
      - shogi_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shogi_db:5432/mydatabase
      SPRING_DATASOURCE_USERNAME: dkh634
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    volumes:
      - ./build/libs:/app/build/libs  # ボリューム追加
    networks:
      - app_network

      
  shogi_db:
    image: postgres:latest
    container_name: shogi_postgres
    restart: always
    environment:
      POSTGRES_USER: dkh634
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:
  
networks:
  app_network: